"""WebSocket market-stream endpoint backed by the live Redis event bus."""

import asyncio
import json
from collections.abc import AsyncIterator
from typing import Any

from fastapi import APIRouter, WebSocket, WebSocketDisconnect

from app.market.models import MarketEvent

router = APIRouter(prefix="/api/v1/market-data", tags=["market-data"])


class MarketEventHub:
    """Fan out canonical market events to WebSocket subscribers.

    Redis delivery is intentionally kept outside the hub so the transport remains
    testable. The application runtime subscribes Redis and forwards validated
    events here; no synthetic events are generated by this component.
    """

    def __init__(self) -> None:
        self._subscribers: dict[str, set[asyncio.Queue[str]]] = {}

    async def subscribe(self, instrument_id: str) -> AsyncIterator[str]:
        queue: asyncio.Queue[str] = asyncio.Queue()
        subscribers = self._subscribers.setdefault(instrument_id, set())
        subscribers.add(queue)
        try:
            while True:
                yield await queue.get()
        finally:
            subscribers.discard(queue)
            if not subscribers:
                self._subscribers.pop(instrument_id, None)

    async def publish(self, event: MarketEvent) -> None:
        payload = event.model_dump_json()
        for queue in tuple(self._subscribers.get(event.instrument_id, ())):
            await queue.put(payload)

    async def publish_payload(self, payload: str) -> None:
        """Forward a Redis JSON event after canonical validation."""
        event = MarketEvent.model_validate_json(payload)
        await self.publish(event)


market_event_hub = MarketEventHub()


async def consume_redis_events(redis_client: Any, *, channel: str = "market.events") -> None:
    """Subscribe to Redis market events and forward them to WebSocket clients.

    Invalid payloads are rejected rather than broadcast. Redis disconnects are
    allowed to propagate so the application can mark the market stream degraded.
    """
    pubsub = redis_client.pubsub()
    await pubsub.subscribe(channel)
    try:
        async for message in pubsub.listen():
            if message.get("type") != "message":
                continue
            payload = message.get("data")
            if isinstance(payload, bytes):
                payload = payload.decode("utf-8")
            if not isinstance(payload, str):
                continue
            await market_event_hub.publish_payload(payload)
    finally:
        await pubsub.unsubscribe(channel)
        await pubsub.close()


@router.websocket("/stream/{instrument_id}")
async def market_stream(websocket: WebSocket, instrument_id: str) -> None:
    await websocket.accept()
    try:
        async for payload in market_event_hub.subscribe(instrument_id):
            await websocket.send_text(payload)
    except WebSocketDisconnect:
        return
